# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lab1(object):
    def setupUi(self, Lab1):
        Lab1.setObjectName("Lab1")
        Lab1.resize(367, 0)
        self.label = QtWidgets.QLabel(Lab1)
        self.label.setGeometry(QtCore.QRect(20, 20, 64, 36))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Lab1)
        QtCore.QMetaObject.connectSlotsByName(Lab1)

    def retranslateUi(self, Lab1):
        _translate = QtCore.QCoreApplication.translate
        Lab1.setWindowTitle(_translate("Lab1", "Form"))
        self.label.setText(_translate("Lab1", "Lab1"))
