# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\untitled4.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lab4(object):
    def setupUi(self, Lab4):
        Lab4.setObjectName("Lab4")
        Lab4.resize(400, 300)
        self.label = QtWidgets.QLabel(Lab4)
        self.label.setGeometry(QtCore.QRect(40, 20, 64, 36))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        #CipherViginer
        self.radioButton = QtWidgets.QRadioButton(Lab4)
        self.radioButton.setGeometry(QtCore.QRect(20, 70, 100, 25))
        self.radioButton.setObjectName("radioButton")
        #CipherWhatstona
        self.radioButton_2 = QtWidgets.QRadioButton(Lab4)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 90, 100, 25))
        self.radioButton_2.setObjectName("radioButton_2")

        self.retranslateUi(Lab4)
        QtCore.QMetaObject.connectSlotsByName(Lab4)

    def retranslateUi(self, Lab4):
        _translate = QtCore.QCoreApplication.translate
        Lab4.setWindowTitle(_translate("Lab4", "Form"))
        self.label.setText(_translate("Lab4", "Lab4"))
        self.radioButton.setText(_translate("Lab4", "CipherVeginer"))
        self.radioButton_2.setText(_translate("Lab4", "CipherWitstone"))
