# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lab3(object):
    def setupUi(self, Lab3):
        Lab3.setObjectName("Lab3")
        Lab3.resize(369, 0)
        self.label = QtWidgets.QLabel(Lab3)
        self.label.setGeometry(QtCore.QRect(20, 20, 64, 36))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.radioButton = QtWidgets.QRadioButton(Lab3)
        self.radioButton.setGeometry(QtCore.QRect(20, 70, 82, 17))
        self.radioButton.setObjectName("radioButton")

        self.retranslateUi(Lab3)
        QtCore.QMetaObject.connectSlotsByName(Lab3)

    def retranslateUi(self, Lab3):
        _translate = QtCore.QCoreApplication.translate
        Lab3.setWindowTitle(_translate("Lab3", "Form"))
        self.label.setText(_translate("Lab3", "Lab3"))
        self.radioButton.setText(_translate("Lab3", "PlayferCipher"))
